acceptedIPs:
  - ::ffff:127.0.0.1
  - ::1
  - ::ffff:88.97.10.194
  - ::ffff:192.168.1.1
  - localhost
mongodbURL : mongodb://localhost/chloetarot
key: test
cert: test
dbUser: admin
dbPassword: admin
